# workflow name
name: Auto Deploy to Github Pages

# master branch on push, auto run
on: 
  push:
    branches:
      - master

jobs:
  Deploy-Pages: 
    runs-on: ubuntu-latest 

    steps:
    # check it to your workflow can access it
    # from: https://github.com/actions/checkout
    - name: Checkout Repository master branch
      uses: actions/checkout@v3

    # from: https://github.com/actions/setup-node  
    - name: Setup Node.js 10.x 
      uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Setup Git Infomation
      run: | 
        git config --global user.name 'bbaa' 
        git config --global user.email 'bbaa_bbaa@qq.com'  

    - name: Setup Dependencies
      run: |
        yarn

    - name: Generate public files
      run: |
        yarn webpack

    - name: Deploy To Github Pages 
      env:
        Github_Pages: github.com/bbaa-bbaa/writtenread-killer.git
        Github_Token: ${{ secrets.token_GithubAPI }}
      run: |  
        yarn gh-pages -d dist -m "Auto deploy" -r "https://${Github_Token}@${Github_Pages}" -f

